### ISSUE TITLE
Add 2014 support

### ISSUE THREAD

**Issue by mzsanford** [dmastylo/Inflation#1]
I can't find your data source to create a pull request

**Comment by dmastylo** [comment]
I didn't realize anyone actually used this, thanks for the issue!

I should have included my data source when I made this, but I neglected to have that foresight at the time. I have found a nearly equivalent source: http://www.minneapolisfed.org/community_education/teacher/calc/hist1800.cfm

However, it looks like 2012 and 2013 have slightly different CPI values from what is in my code; shouldn't be an issue though.

**Comment by mzsanford** [comment]
added
